version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "staging-whoami"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service << parameters.k8s_svc_name >>
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN apply -f k8s/whoami-deployment.yml

deploy_production:
    docker:
      - image: circleci/node:9.8.0-stretch
    steps:
      - k8s_deploy:
          k8s_svc_name: "production-whoami"

tagged_release_production:
    jobs:
      - build_push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
      - deploy_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
