apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: whoami
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: circleci-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: circleci-controller
subjects:
- kind: ServiceAccount
  name: circleci
  apiGroup: rbac.authorization.k8s.io